mode:
  develop: true

server:
  port: 8090

db:
#  dsn: root:sr990611@tcp(127.0.0.1:3306)/gorm?charset=utf8mb4&parseTime=True&loc=Local
  dsn: db6251:Southampton1024@tcp(db6251.mysql.database.azure.com:3306)/db6251?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 # 最多空闲连接数
  maxOpenConn: 10 # 最多打开连接数

redis:
  url: redis6251.redis.cache.windows.net:6379

jwt:
  tokenExpire: 30        # token有效时长(分钟)
  signingKey: localservice # 签名使用的Key


log:
  MaxSize: 1      # 日志文件最大的尺寸(M), 超限后开始自动分割
  MaxBackups: 10  # 保留旧文件的最大个数
  MaxAge: 90      # 保留旧文件的最大天数